### ISSUE TITLE
Add CZ, HR, HU, SK, SI, RS, BG, GR, EE, FI, LT, LV, NO, PL, RO, UA values to data-lang attribute

### ISSUE THREAD

**Issue by Tubilopto** [FriendlyCaptcha/friendly-challenge#120] opened 2022-06-16 15:04 UTC
Hello,

Could you please add CZ, HR, HU, SK, SI, RS, BG, GR, EE, FI, LT, LV, NO, PL, RO, UA values to **data-lang** attribute for respectively Czech, Croatian, Hungarian, Slovakian, Slovenian, Serbian, Bulgarian, Greek, Estonian, Finnish, Lithuanian, Latvia, Norwegian, Polish, Romanian and Ukrainian languages? We are in the middle of a big rollout and it would be amazing to have translations working for these languages :)

Best,

Tugba

**Comment by merlinfuchs** [comment] 2022-06-20 18:50
We usually let native speakers do the translations for us. If you know anyone that speaks one of these languages they can always create a PR here.

**Comment by dev-love** [comment] 2022-06-22 15:10
@merlinfuchs Maybe we can try to find a more efficient way of loading languages for the widget. The more languages we have, the better in general, I'd say. But of course this should not harm loading performance too much.

**Comment by gzuidhof** [comment] 2022-06-22 15:40
### How much does the bundle size increase

I guesstimate that every language we add adds around 500 bytes to the bundle, and 200 bytes to the bundle after gzip. These 16 languages listed here I assume would add 3.2kb or so to the file actually downloaded by end users. This is a significant increase (from around 12kb to 15kb for the non-polyfilled modern browser version). 

But pragmatically 3kb isn't something to worry about. Our widget generally loads after the webpage loads so a 0.1 second longer load time isn't that critical. It hurts me to say that as we worked quite hard to get our stuff so small! 

For comparison: Google ReCAPTCHA uses almost 1.5MB, a thousand times as much, and I wasn't even shown any challenge (so no challenge images were loaded), here's a screenshot of their demo page:
<img width="1798" alt="Screenshot 2022-06-22 at 17 36 20" src="https://user-images.githubusercontent.com/1039510/175073005-21d5d54c-e2ab-42a0-a025-8c067618602d.png">

### How could we do it differently
In the future

We could include languages with a separate JS file that can be included that 'registers' the language for this library, that way website admins could include only those languages they are interested in. In a future (v2) widget we will also be able to load the languages on-demand as we are moving to more serverside 'rendering'.

### Conclusion
I'm happy to include more languages as long as we can have confidence they are correct and came from a (near)-Native speaker. Google Translate powered translations usually do more harm than good (in most cases users are better off with English then)

**Comment by Tubilopto** [comment] 2022-06-23 07:53
Hi everyone, thanks a lot for the support and clear explanations here! :)
I will be providing the translations to you in the upcoming days, they will be provided by the markets themselves. 
Another questions is: would you like us to provide them as it is in the code? Maybe it would be easier for you to implement.
Example:
`// English
const LANG_EN: Localization = {
  text_init: "Initializing..",

  text_ready: "Anti-Robot Verification",
  button_start: "Click to start verification",

  text_fetching: "Fetching Challenge",

  text_solving: "Verifying you are human..",
  text_completed: "I am human",
  text_completed_sr: "Automatic spam check completed",

  text_expired: "Anti-Robot verification expired",
  button_restart: "Restart",

  text_error: "Verification failed",
  button_retry: "Retry",
  text_fetch_error: "Failed to connect to",
};`

**Comment by gzuidhof** [comment] 2022-07-15 00:06
This is now merged and published as part of version 0.9.5. In the end the extra bundle size is ~3KB:
<img width="319" alt="Screenshot 2022-07-15 at 02 05 18" src="https://user-images.githubusercontent.com/1039510/179121012-0e0eb970-5906-468c-a9a9-e54f6979281c.png">

**Comment by gzuidhof** [comment] 2022-07-15 09:41
Hi Tugba,

Could you ensure you are on version 0.9.5? I am not able to reproduce the issue, here's a screenshot of a Czech widget.
<img width="318" alt="Screenshot 2022-07-15 at 11 36 39" src="https://user-images.githubusercontent.com/1039510/179197531-8b89b98a-0a1e-4c29-9a9a-b35da8703c87.png">

The version on NPM via a CDN looks to contain the new languages too:

<img width="824" alt="Screenshot 2022-07-15 at 11 39 26" src="https://user-images.githubusercontent.com/1039510/179197817-117e0802-eef9-480e-9d7d-e21be3d9c369.png">



We will need to update the Wordpress plugin still with this latest version, are you using that by any chance?

**Comment by Tubilopto** [comment] 2022-07-15 09:46
Hello Guido,

I understand the issue now; we are using 0.9.2 still. I'll update it.

But should we be always on top of new versions? Since this the link we are implementing on Sitecore, it would require us to always check if there is a new version, and update it. Is there any other way where you can update the version without us having to also update it?

https://unpkg.com/friendly-challenge@0.9.5/widget.module.min.js

Best,

Tugba

**Comment by gzuidhof** [comment] 2022-07-15 09:53
We aim for the widget code to be as stable as possible, if the current version works for you then you shouldn't have to update the widget :) - but it's of course never a bad idea to update at least once a year or so. We have users using versions of the widget from one and a half year ago without issues - but they are missing out on some fixes and improvements.

We're working on version two of our captcha offering which will be served a bit differently, in that version we will be able to update parts in the background such as the localizations :).

Have a great weekend!

**Comment by Tubilopto** [comment] 2022-07-15 10:12
I understand, thank you so much! :)

I have updated it to 0.9.5 in the backend but still the translations are not visible. Could you please check?

https://www.nivea.bg/#layer=contact-us

**Comment by gzuidhof** [comment] 2022-07-15 11:27
I looked at the source code of the webpage, from the looks of it the version of the widget that is live is `0.9.0`.

I imagine there is something internal to your organization that hasn't processed your update yet, so I'm afraid I can't provide useful pointers there. Maybe changes to production happen once per day or week? This is something the team that manage/deploy the Nivea websites can hopefully clear up for you

**Comment by gzuidhof** [comment] 2022-07-15 11:47
When I was trying the different localizations I noticed that in some translations the button text (`"button_start"`) overflows (here in Bulgarian): 

<img width="320" alt="Screenshot 2022-07-15 at 13 29 40" src="https://user-images.githubusercontent.com/1039510/179215146-4d85a536-8350-4048-9ba2-1f33dd672955.png">

99% of people don't press (or even see) the button as it automatically starts solving when the form is clicked, so it's not the end of the world, but I would be happy to include changes to the localizations that make these button texts a bit shorter.

---

I think a maximum number of characters that fit is approximately:
* 32 cyrillic characters
* 38 latin characters.

The text could be something like *"Click to start"* or *"Click to verify"* instead of *"Click to start verification"* in languages that are a bit too wide.

Languages that could be shortened a bit:
* Greek
* Ukranian
* Bulgarian
* Serbian (it actually fits, but it's so tight that it's not the prettiest)
* Hungarian

**Comment by Tubilopto** [comment] 2022-08-02 11:05
Thanks a lot Guido! We will check the translations after our internal bug is fixed. 

Meanwhile, could you please update FI and DA languages? 

[Friendly Captcha SE,FI.txt](https://github.com/FriendlyCaptcha/friendly-challenge/files/9241601/Friendly.Captcha.SE.FI.txt)

Thank you!

Tubi

**Comment by gzuidhof** [comment] 2022-08-08 09:17
Re-opening this so we don't forget about this, thank you for the updated translations! :)

**Comment by Tubilopto** [comment] 2022-09-07 11:20
Hello! I am opening this again because NO translation do not work from our side; all the other languages are fine:
https://www.nivea.no/#layer=contact-us
Could you please check?

**Comment by merlinfuchs** [comment] 2022-09-07 16:39
You seem to be providing `nb` as the language code instead of `no`. Seems like both are valid language codes for norwegian, but `no` is the primary one. 
Changing it from `nb` to `no` should solve the issue. If this is a dealbreaker I think we can add `nb` as an alias for `no`.

**Comment by Tubilopto** [comment] 2022-09-08 10:56
It would require a lot of efforts from our side unfortunately. If adding nb as an alias for no is gonna work on the frontend, it would be amazing :)
Thank you!

**Closed** 2022-09-08 17:20 UTC

**Comment by merlinfuchs** [comment] 2022-09-08 17:21
I have added `nb` as an alias for `no`. This will be part of the next update, but I'm not sure when we will be rolling it out

**Comment by merlinfuchs** [comment] 2022-09-08 17:22
@gzuidhof will probably roll it out next week :)

**Comment by merlinfuchs** [comment] 2022-09-15 12:23
Hey, please check the comments above (https://github.com/FriendlyCaptcha/friendly-challenge/issues/120#issuecomment-1239630557).
Norwegian translations should start working when you update the Wordpress plugin.

**Comment by merlinfuchs** [comment] 2022-09-15 16:56
Please make sure you are using the most recent version of the widget. The `nb` alias for `no` is only available in the most recent version.
