### ISSUE TITLE
Initial captcha check fails

### ISSUE THREAD

**Issue by Seache** [FriendlyCaptcha/friendly-challenge#72] opened 2022-01-14 19:29 UTC
Hello,
unfortunately I encounter the same issue as [Initial captcha fails #62](https://github.com/FriendlyCaptcha/friendly-challenge/issues/62) :
on page load the captcha starts automatically and creates a solution string. The first check always fails with
`data: { success: false, details: 'puzzle solutions invalid', errors: [ 'solution_invalid' ] }`

Then a new solution string is generated and if I submit again it is working fine.
I compared the fresh generated solution string with the one passed to the backend after sending the post request and they are identically, so no it does not get malformed on the way.

Two example solution strings:
This one is initially created and returns `success: false`:
`044d72cdaf6def6ba903269d2dd2883a.YeCtcNtr6o1VJ68sAQwtjQAAAAAAAAAANyOR2rXnAfE=.AAAAAP5dAAABAAAAAZUAAAIAAABVsgMAAwAAABUaAgAEAAAA5KsAAAUAAADoQgEABgAAALnWBgAHAAAAI8sJAAgAAAAceQwACQAAAMV5AAAKAAAAUskAAAsAAACGnQ0ADAAAABliAAANAAAAJkkAAA4AAADtHgEADwAAAAnkBwAQAAAA9pABABEAAAAcbgAAEgAAAPLMAwATAAAAyh8AABQAAAB7jAAAFQAAALSEAAAWAAAAW+8MABcAAAB9XwIAGAAAAKNwDAAZAAAASLUAABoAAACGpQMAGwAAAF3MAwAcAAAAv6EPAB0AAABQ9gAAHgAAAIu5BAAfAAAA6o8FACAAAABG2QQAIQAAALP0GAAiAAAAVF0CACMAAAC1tQAAJAAAALSoBwAlAAAA1e0AACYAAAC3OgAAJwAAAIF7AQAoAAAA2IYAACkAAACysgAAKgAAAGNnAQArAAAAiCYKACwAAADGpgQA.AgAG`

This one is generated next and returns `success: true`:
`137ecf6c989f4f9704298743f4981d7b.YeCrU9tr6o1VJ68sAQwtjQAAAAAAAAAA1n6rVk2GJrg=.AAAAAJSzAQABAAAAdUMAAAIAAAA3OQAAAwAAALXkAAAEAAAA0iwDAAUAAAAPNwAABgAAAEzFCAAHAAAAtTQEAAgAAABHRwAACQAAAOxAAQAKAAAAwNkAAAsAAACcVwAADAAAAIL3AgANAAAAy5UKAA4AAADg0AAADwAAANmkAAAQAAAAoZEAABEAAAA6JgAAEgAAAGu5AgATAAAA4fQAABQAAABAagMAFQAAAEijAQAWAAAADFIHABcAAABcmAAAGAAAANH1AQAZAAAAMIAAABoAAAAfxAAAGwAAACMEAAAcAAAASWsDAB0AAACK7wAAHgAAAD8uBAAfAAAAkp8BACAAAAAxhgYAIQAAABblAgAiAAAAtogAACMAAADd7gEAJAAAAIwSAQAlAAAA5BsJACYAAABJzwAAJwAAAAftAQAoAAAAnIcIACkAAACR2gAAKgAAAMZmAwArAAAAwPQBACwAAABkRgAA.AgAD`

I cannot see a difference there.
Does anyone know what the problem could be?

Thank you!

**Comment by gzuidhof** [comment] 2022-01-17 00:14
Hi Seache,

I'm not sure why this is happening and it's not something that is immediately obvious (there don't seem to be any encoding issues). I can try to validate the answer at some point but that requires some manual effort on my end (and if it shows that the puzzle is actually invalid then it still wouldn't help much in finding the reason why). 

Could you check on your server just before sending it to our siteverify endpoint? The first answer has a `+` in it: maybe your server has trouble encoding that? (Similar to what we saw in #62): that is probably the best first step in figuring this out.

**Comment by Seache** [comment] 2022-01-17 21:25
Hello Guido,

thank you for your answer.
Sure, this is the solution string (initial one which failed) just before sending it to the siteverify endpoint:
`885116beebe0b0cab0dc12e6691d01b1.YeXcLNtr6o1VJ68sAQwtjQAAAAAAAAAAghCGyzZTZbc=.AAAAAF29AAABAAAAqckIAAIAAAAygwQAAwAAAP80AQAEAAAApfcQAAUAAADXWAAABgAAABbSAwAHAAAA2GkAAAgAAACTsgEACQAAAJfwBgAKAAAABN8EAAsAAACkHgUADAAAAE/lAAANAAAAKYsDAA4AAAAHPQAADwAAAOeFCwAQAAAAcuIAABEAAAAk9gAAEgAAAKAfBQATAAAAbkgBABQAAACmSQEAFQAAAH/pBQAWAAAA844BABcAAADQFwcAGAAAAOh1AgAZAAAAR60AABoAAABYXgEAGwAAAGp+AAAcAAAATgEBAB0AAADhBgAAHgAAABW2AAAfAAAAc30JACAAAADSxwoAIQAAAD8WAwAiAAAA8JgAACMAAABb1AQAJAAAAHjUAgAlAAAAvAcFACYAAADKMQoAJwAAABZBAAAoAAAAWG8HACkAAACCUwYAKgAAALCvAAArAAAAHMgFACwAAADWXwwA.AgAG`

It still has a `+` char in it.

After a new solution string was generated I submitted the form again and it worked with this one:
`0fddc3fc6d79ff38e00b57abc088481b.YeXcPttr6o1VJ68sAQwtjQAAAAAAAAAAxmTBkWlxhWo=.AAAAAODXCgABAAAApDYGAAIAAABocQEAAwAAAFxMAAAEAAAAccIFAAUAAADffQAABgAAAPCZBAAHAAAAARYAAAgAAAAi/wMACQAAAPZbBQAKAAAATZAHAAsAAADp+gUADAAAAI8oAgANAAAAbV8BAA4AAAAwmBQADwAAAFHlBAAQAAAA7ysBABEAAADTmwEAEgAAAHwPBwATAAAAH7YDABQAAADHywQAFQAAAIG2AQAWAAAA9OYEABcAAADmhgQAGAAAAJR9AQAZAAAADBcBABoAAABiowIAGwAAAJ4dAAAcAAAATPMPAB0AAACMfwQAHgAAAN3oBAAfAAAAErIAACAAAABWFgIAIQAAABEKBQAiAAAA/iwCACMAAACZrwMAJAAAAEljAgAlAAAA3MIBACYAAADKawEAJwAAAKbQAgAoAAAAIxMCACkAAAAhYwEAKgAAALwAAQArAAAA4yYAACwAAACwWgIA.AgAG`

This one also contains a `+`, so I think this is not the issue.

Do you have any ideas what else it could be?

**Comment by gzuidhof** [comment] 2022-01-31 17:38
Hi Seache,

It's been a while that you posted this issue, but I finally got around to looking into this a bit more in-depth.
* When I put the given puzzles into a solver manually for the ones that fail it finds a different solution (which is weird: as the solver should be deterministic).
* When I put in the succesful solution, it indeed finds the same solution.

I suspect there is an issue in the front-end widget (and perhaps how it ties into React), and very unlikely in your backend code (or our verification service). The next step is to try and reproduce it with a minimal example.

**Comment by Seache** [comment] 2022-02-04 20:40
Hello Guido,
thank you for your answer and investigation. Please keep me updated.

**Comment by gzuidhof** [comment] 2022-03-10 15:26
With #90 this should be fixed, feel free to re-open if you run into it again. We haven't minted a release yet, but I expect 0.9.2 will be available soon (next week or so).

**Closed by gzuidhof** 2022-03-10 15:26 UTC
