### ISSUE TITLE
Block by CORS on Cloudflare

### ISSUE THREAD

**Issue by dev-love** [FriendlyCaptcha/friendly-challenge#47] opened 2021-06-29 10:39 UTC
Request by André Bonna:

When I click in the button to verify my website the friendly challange code requests:

Request URL: https://api.friendlycaptcha.com/api/v1/puzzle?sitekey=FCMSH93UHD61PBUB
Request Method: OPTIONS
Status Code: 403 
Remote Address: 172.67.219.80:443
Referrer Policy: strict-origin-when-cross-origin

The response headers are:

alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
cf-chl-bypass: 1
cf-ray: 6668476ddc044d1b-GRU
cf-request-id: 0af50af8ab00004d1b6a881000000001
content-encoding: br
content-type: text/html; charset=UTF-8
date: Mon, 28 Jun 2021 16:26:49 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 01 Jan 1970 00:00:01 GMT
nel: {"report_to":"cf-nel","max_age":604800}
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=z6w8KxnYysI5HUy7W27Bve%2BW6XXYZsW2BOrnlEDM6QSYZT59YxBbF69cYerIG%2FdhheX7J6Oi%2F%2FrsBHxjQ1OqNhK1O2lGWC%2FVX%2FxaZtr6Jf6kuZH23YZLUR%2FsQ5nkMGXRs0bXjAo%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Accept-Encoding
x-frame-options: SAMEORIGIN

**Comment by gzuidhof** [comment] 2021-06-29 12:11
It appears this request never made it to our own servers and instead bounced at the Cloudflare level, a small peek into our backend handler for this endpoint in the worker, this is pretty much the first thing:

```javascript
  if (request.method === "OPTIONS") {
    return new Response(null, {headers: getCorsHeaders(request), status: 200});
  }
```

None of these CORS headers are present in the response here. Is this a persistent issue? I am unable to reproduce it in Postman:

<img width="1346" alt="Screenshot 2021-06-29 at 13 10 14" src="https://user-images.githubusercontent.com/1039510/123795023-6e021600-d8db-11eb-8704-54b10af06cfb.png">

**Comment by gzuidhof** [comment] 2021-09-16 14:50
I'm closing this issue as we haven't seen it since - let's re-open if we ever run into this again.

**Closed by gzuidhof** 2021-09-16 14:50 UTC

**Comment by smolnos** [comment] 2022-02-28 11:21
We had also added FriendlyCaptcha to our Covid 19 website. Everything was working fine until a week ago when we suddenly received the error "Cross-Origin Request Blocked": Same Origin Policy prohibits reading of remote resource at https://api.friendlycaptcha.com/api/v1/siteverify. (Reason: CORS header 'Access-Control-Allow-Origin' is missing), even though we hadn't changed it at all.

**Comment by merlinfuchs** [comment] 2022-02-28 14:31
@smolnos You are most likely experiencing this issue because you are using the siteverify endpoint from the client side. This is not the intended usage, you must have a backend that makes the request to the sitevery endpoint to validate a puzzle solution. You are otherwise exposing the API secret to anyone that is using your website and make the captcha very easy to bypass.

**Comment by smolnos** [comment] 2022-03-09 15:17
Thank you very much for your answer. I tried to put everything in the backend, but I don't have the experience for that. This is especially difficult because I have not found an example of backend. 
For this reason I would like to leave the software as it is. Is it possible that it does not work (since it worked until 2 weeks ago) that we did not pay the bill on time?

**Comment by merlinfuchs** [comment] 2022-03-09 19:22
You can find an example for the backend code in https://github.com/FriendlyCaptcha/friendly-captcha-examples/blob/main/nextjs/pages/api/submitBasic.js#L3. It's just making a HTTP request to the sitevery endoint with the provided solution and checks if it's valid. This is probably similar to what you have been doing on the client side.

You are experiencing this because we have made changes to the API to prevent people from using it in a wrong way. By making the siteverify request from the client you are basically eliminating any security provided by the captcha.

**Comment by smolnos** [comment] 2022-03-17 18:18
Hi merlinfuchs,
Thank you very much for the example. I tried to adapt the example for vue3  (frontend) and php (backend), but unfortunately it is not so easy. That's why I would like to know if there is an example also for vue3 and php? Thanks a lot!

**Comment by merlinfuchs** [comment] 2022-03-21 11:04
We currently don't have any backend examples. But it's basically just a single http request that you need to implement in the backend. You will probably want to use `cURL` for that in PHP.
Maybe the PHP code of our Wordpress plugins will help you to implement it: https://github.com/FriendlyCaptcha/friendly-captcha-wordpress/blob/main/friendly-captcha/includes/verification.php
