### ISSUE TITLE
Scoping global variables/variablename when loading the FC script

### ISSUE THREAD

**Issue by dev-love** [FriendlyCaptcha/friendly-challenge#101] opened 2022-05-11 16:22 UTC
Hey, there seems to be a problem of scoping global variables/variablename when loading the FC script. Somewhere the (probably minified( identifier "i" has been declared as a constant variable containing "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/". This blocks other scripts from loading correctly so it might probably have to be fixed.
Could you please check this if its caused by FC?

**Comment by gzuidhof** [comment] 2022-05-13 11:21
This kind of issue is usually caused by a third party minifier that misbehaves (often a wordpress plugin that tries to optimize or combine scripts for loading speed).

I went to the test page that's served with the library [here](https://unpkg.com/friendly-challenge@0.9.2/index.html) and there are no variables leaking in scope from what I could tell. 

The solution for this user is to add our scripts as an exception in whichever plugins they are using. I'll close this issue and re-open it if we learn something else is causing this

**Closed by gzuidhof** 2022-05-13 11:21 UTC
